prompt --application/pages/page_00007
begin
--   Manifest
--     PAGE: 00007
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.10.07'
,p_release=>'22.2.0'
,p_default_workspace_id=>1408791537380179
,p_default_application_id=>101
,p_default_id_offset=>0
,p_default_owner=>'HR'
);
wwv_flow_imp_page.create_page(
 p_id=>7
,p_name=>'STD_DML'
,p_alias=>'STD-DML'
,p_step_title=>'STD_DML'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'18'
,p_last_updated_by=>'AVADHUT'
,p_last_upd_yyyymmddhh24miss=>'20230314121506'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(3070681130435004)
,p_plug_name=>'STD_DML'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(1475297932738559)
,p_plug_display_sequence=>10
,p_query_type=>'SQL'
,p_plug_source=>'SELECT * FROM STUDENTS@MYLINK003;'
,p_plug_source_type=>'NATIVE_IR'
,p_prn_page_header=>'STD_DML'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(3070703350435004)
,p_name=>'STD_DML'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_base_pk1=>'id'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'C'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_detail_link=>'f?p=&APP_ID.:8:&APP_SESSION.::&DEBUG.:RP:P8_ID:\#id#\'
,p_detail_link_text=>'<span aria-label="Edit"><span class="fa fa-edit" aria-hidden="true" title="Edit"></span></span>'
,p_owner=>'AVADHUT'
,p_internal_uid=>3070703350435004
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3071106783435015)
,p_db_column_name=>'id'
,p_display_order=>0
,p_column_identifier=>'A'
,p_column_label=>'Id'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3071504317435020)
,p_db_column_name=>'name'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Name'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3071946974435020)
,p_db_column_name=>'class'
,p_display_order=>3
,p_column_identifier=>'C'
,p_column_label=>'Class'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(3073038346435873)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'30731'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'id:name:class'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(3072498094435021)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_imp.id(3070681130435004)
,p_button_name=>'CREATE'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(1591222689738667)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Create'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_button_redirect_url=>'f?p=&APP_ID.:8:&APP_SESSION.::&DEBUG.:8::'
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(3027785703105911)
,p_process_sequence=>10
,p_process_point=>'AFTER_SUBMIT'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'CREATE'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'STD_MAINTAIN.INSERT_STUDENTS(',
'    :id,',
'    :name,',
'    :class);'))
,p_process_clob_language=>'PLSQL'
,p_process_error_message=>'inserted'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_imp.id(3072498094435021)
,p_process_success_message=>'inserted'
);
wwv_flow_imp.component_end;
end;
/
